spring:
  application:
    name: kids-castle-preschool-service
server:
  port: 9002

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.12.222:9000/eureka/
  instance:
    prefer-ip-address: true
